import React,{useEffect,useRef,useState} from 'react';
import {Link,useLocation} from 'react-router-dom';
import {ArrowUpRight,Menu,X,Play,ChevronDown,Check,LogOut,Radio,BrainCircuit,Scan,Map,LayoutDashboard,Sliders} from 'lucide-react';
import {api} from '../services/api';
interface NavbarProps{currentRole?:string|null;onLogout?:()=>void;onRoleChange?:(role:string)=>void}
export const Navbar:React.FC<NavbarProps>=({currentRole='FARMER',onLogout,onRoleChange})=>{
 const location=useLocation();const [health,setHealth]=useState<'ONLINE'|'OFFLINE'>('ONLINE');const [menu,setMenu]=useState(false);const [user,setUser]=useState(false);const [ops,setOps]=useState(false);const ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{let live=true;const check=async()=>{try{await api.getHealth();if(live)setHealth('ONLINE')}catch{if(live)setHealth('OFFLINE')}};check();const id=setInterval(check,10000);return()=>{live=false;clearInterval(id)}},[]);
 useEffect(()=>{setMenu(false);setUser(false);setOps(false)},[location.pathname]);
 const primary=[['/','01','FIELD COMMAND',LayoutDashboard],['/intelligence','02','INTELLIGENCE',BrainCircuit],['/scan','03','SCAN PLANT',Scan],['/map','04','FARM MAP',Map]] as const;
 const operations=[['/sprayer','05','SPRAYER',Radio],['/analytics','06','ANALYTICS',Sliders]] as const;
 return <header className="tathva-nav sticky top-0 z-50"><div className="max-w-[1500px] mx-auto px-4 sm:px-6 lg:px-10"><div className="h-[74px] flex items-center justify-between gap-5">
  <Link to="/" className="tathva-brand"><span className="brand-mark">AP</span><span className="brand-name">AGRIPRESCRIBE</span><span className="brand-tag">/ FIELD INTELLIGENCE</span></Link>
  <nav className="hidden lg:flex items-center gap-1">{primary.map(([path,num,label,I])=><Link key={path} to={path} className={`tathva-nav-item ${location.pathname===path?'active':''}`}><span>{num}/</span><I/><b>{label}</b></Link>)}<div className="relative" ref={ref}><button onClick={()=>setOps(!ops)} className={`tathva-nav-item ${ops?'active':''}`}><span>05/</span><Sliders/><b>OPERATIONS</b><ChevronDown/></button>{ops&&<div className="tathva-dropdown"><Link to="/sprayer">SPRAYER CONTROL</Link><Link to="/history">MISSION HISTORY</Link><Link to="/analytics">ANALYTICS</Link><Link to="/audit">AUDIT LOG</Link><Link to="/storage">STORAGE</Link></div>}</div></nav>
  <div className="flex items-center gap-2"><Link to="/demo" className="tathva-cta hidden sm:flex"><Play/><span>LIVE DEMO</span><ArrowUpRight/></Link><span className={`tathva-status hidden md:flex ${health==='OFFLINE'?'offline':''}`}><i/> {health}</span><div className="relative"><button onClick={()=>setUser(!user)} className="tathva-user">{currentRole?.[0]||'F'}<ChevronDown/></button>{user&&<div className="tathva-user-menu">{['FARMER','AGRONOMIST','ADMIN'].map(r=><button key={r} onClick={()=>{onRoleChange?.(r);setUser(false)}}>{r}{currentRole===r&&<Check/>}</button>)}<button className="danger" onClick={()=>onLogout?.()}><LogOut/>SIGN OUT</button></div>}</div><button className="lg:hidden tathva-menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></div>
  {menu&&<div className="lg:hidden tathva-mobile">{[...primary,...operations].map(([path,num,label,I])=><Link key={path} to={path}><span>{num}/</span><I/><b>{label}</b></Link>)}</div>}
 </div><div className="tathva-marquee"><span>/// PRECISION AGRICULTURE /// AI CROP INTELLIGENCE /// WEATHER-AWARE SPRAY WINDOWS /// SMART FIELD OPERATIONS /// </span><span>/// PRECISION AGRICULTURE /// AI CROP INTELLIGENCE /// WEATHER-AWARE SPRAY WINDOWS /// SMART FIELD OPERATIONS /// </span></div></header>;
};
