import React,{createContext,useContext,useEffect,useMemo,useState} from 'react';
export type Lang='en'|'hi'|'ml';
const dict:Record<Lang,Record<string,string>>={
 en:{overview:'Overview',intelligence:'Intelligence',scan:'Plant Scan',map:'Farm Map',operations:'Operations',demo:'Demo',role:'Role',signout:'Sign Out',sprayer:'Sprayer Control & Missions',storage:'Chemical Storage & Stock',history:'Spray Mission History',analytics:'Analytics & ROI',audit:'Compliance & Audit Logs',knowledge:'Knowledge Base Admin',field:'Field',weather:'Weather',healthy:'Healthy',monitor:'Monitor',startScan:'Scan a plant',openMap:'Open farm map',checkWeather:'Check weather',controlSprayer:'Sprayer controls',farmerHelp:'Farmer quick actions',language:'Language',online:'ONLINE',offline:'OFFLINE'},
 hi:{overview:'मुख्य पृष्ठ',intelligence:'स्मार्ट सलाह',scan:'पौधे की जाँच',map:'खेत का नक्शा',operations:'कार्य',demo:'डेमो',role:'भूमिका',signout:'साइन आउट',sprayer:'स्प्रे मशीन नियंत्रण',storage:'रसायन भंडार',history:'स्प्रे इतिहास',analytics:'बचत व आँकड़े',audit:'रिकॉर्ड व अनुपालन',knowledge:'ज्ञान आधार',field:'खेत',weather:'मौसम',healthy:'स्वस्थ',monitor:'निगरानी',startScan:'पौधे की फोटो लें',openMap:'खेत का नक्शा देखें',checkWeather:'मौसम देखें',controlSprayer:'स्प्रे मशीन',farmerHelp:'किसान के लिए आसान विकल्प',language:'भाषा',online:'ऑनलाइन',offline:'ऑफलाइन'},
 ml:{overview:'പ്രധാന പേജ്',intelligence:'സ്മാർട്ട് നിർദ്ദേശം',scan:'ചെടി പരിശോധിക്കുക',map:'കൃഷിയിട മാപ്പ്',operations:'പ്രവർത്തനങ്ങൾ',demo:'ഡെമോ',role:'പങ്ക്',signout:'സൈൻ ഔട്ട്',sprayer:'സ്പ്രെയർ നിയന്ത്രണം',storage:'രാസവസ്തു സംഭരണം',history:'സ്പ്രേ ചരിത്രം',analytics:'ലാഭവും കണക്കുകളും',audit:'രേഖകളും അനുസരണവും',knowledge:'അറിവ് കേന്ദ്രം',field:'കൃഷിയിടം',weather:'കാലാവസ്ഥ',healthy:'ആരോഗ്യമുള്ളത്',monitor:'നിരീക്ഷിക്കുക',startScan:'ചെടിയുടെ ചിത്രം എടുക്കുക',openMap:'കൃഷിയിട മാപ്പ് കാണുക',checkWeather:'കാലാവസ്ഥ പരിശോധിക്കുക',controlSprayer:'സ്പ്രെയർ',farmerHelp:'കർഷകർക്കുള്ള എളുപ്പ വഴികൾ',language:'ഭാഷ',online:'ഓൺലൈൻ',offline:'ഓഫ്‌ലൈൻ'}
};
const C=createContext<{lang:Lang;setLang:(l:Lang)=>void;t:(k:string)=>string}>({lang:'en',setLang:()=>{},t:k=>k});
export const LanguageProvider:React.FC<React.PropsWithChildren>=({children})=>{const [lang,setLangState]=useState<Lang>(()=>(localStorage.getItem('appLanguage') as Lang)||'en');const setLang=(l:Lang)=>{localStorage.setItem('appLanguage',l);setLangState(l)};useEffect(()=>{document.documentElement.lang=lang},[lang]);const value=useMemo(()=>({lang,setLang,t:(k:string)=>dict[lang][k]||dict.en[k]||k}),[lang]);return <C.Provider value={value}>{children}</C.Provider>};
export const useLanguage=()=>useContext(C);
